apiVersion: 1

datasources:
  - name: Infinity
    type: yesoreyeram-infinity-datasource
    access: proxy
    isDefault: false
    uid: infinity
    jsonData:
      global_queries: []
    version: 1
    editable: true
