#!/usr/bin/env python3
"""Fail closed when a Freqtrade execution mode and database disagree.

Freqtrade's nested environment variables override JSON configuration, so the
guard resolves ``FREQTRADE__DRY_RUN`` and ``FREQTRADE__DB_URL`` first. A live
process must use a live-named database and must never inherit an open trade
whose order id was generated by dry-run execution.
"""

from __future__ import annotations

import argparse
import json
import os
import sqlite3
import sys
from pathlib import Path


FALSE_VALUES = {"0", "false", "no", "off"}
TRUE_VALUES = {"1", "true", "yes", "on"}


class GuardError(RuntimeError):
    """A configuration or position-ledger invariant was violated."""


def _as_bool(value: object, field: str) -> bool:
    if isinstance(value, bool):
        return value
    normalized = str(value).strip().lower()
    if normalized in TRUE_VALUES:
        return True
    if normalized in FALSE_VALUES:
        return False
    raise GuardError(f"{field} has invalid boolean value {value!r}")


def _sqlite_path(db_url: str) -> Path | None:
    prefix = "sqlite:///"
    if not db_url.startswith(prefix):
        return None
    return Path(db_url.removeprefix(prefix))


def validate(config_path: Path) -> dict[str, object]:
    config = json.loads(config_path.read_text())
    dry_run = _as_bool(
        os.environ.get("FREQTRADE__DRY_RUN", config.get("dry_run")),
        "dry_run",
    )
    db_url = str(os.environ.get("FREQTRADE__DB_URL", config.get("db_url", "")))
    if not db_url:
        raise GuardError("db_url is empty")

    lowered_url = db_url.lower()
    expected_marker = ".dryrun." if dry_run else ".live."
    if expected_marker not in lowered_url:
        mode = "dry-run" if dry_run else "live"
        raise GuardError(
            f"{mode} process must use a database containing {expected_marker!r}; "
            f"got {db_url!r}"
        )

    db_path = _sqlite_path(db_url)
    if dry_run or db_path is None or not db_path.exists():
        return {"dry_run": dry_run, "db_url": db_url, "phantom_trades": []}

    connection = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
    try:
        tables = {
            row[0]
            for row in connection.execute(
                "SELECT name FROM sqlite_master WHERE type='table'"
            )
        }
        if not {"trades", "orders"}.issubset(tables):
            return {"dry_run": dry_run, "db_url": db_url, "phantom_trades": []}
        phantom_trades = connection.execute(
            """
            SELECT DISTINCT trades.id, trades.pair, orders.order_id
            FROM trades
            JOIN orders ON orders.ft_trade_id = trades.id
            WHERE trades.is_open = 1
              AND lower(coalesce(orders.order_id, '')) LIKE 'dry_run_%'
            ORDER BY trades.id
            """
        ).fetchall()
    finally:
        connection.close()

    if phantom_trades:
        rendered = ", ".join(
            f"#{trade_id} {pair} ({order_id})"
            for trade_id, pair, order_id in phantom_trades
        )
        raise GuardError(
            "live database contains open dry-run trade records: " + rendered
        )
    return {"dry_run": dry_run, "db_url": db_url, "phantom_trades": []}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", required=True, type=Path)
    args = parser.parse_args()
    try:
        result = validate(args.config)
    except (GuardError, json.JSONDecodeError, OSError, sqlite3.Error) as exc:
        print(f"[db-mode-guard] BLOCKED: {exc}", file=sys.stderr)
        return 78
    mode = "dry-run" if result["dry_run"] else "live"
    print(f"[db-mode-guard] ok: {mode} -> {result['db_url']}", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
