// Consistent, entirely synthetic data shared by the visual preview and browser tests.
module.exports = function fixture(now=Date.now()) {
 const start=now-12*86400000;const bots={};const equities={};const trades=[];
 ['funding-fade','keltner-bounce','killers-ft'].forEach((key,i)=>{
  const pair=['TRX/USDT','FIL/USDT','LINK/USDC:USDC'][i];
  const recent=[.6,i-1.6].map((pnl,j)=>({trade_id:10+i*2+j,pair,is_open:false,open_rate:100,close_rate:100+pnl*4,amount:.25,stake_amount:25,profit_abs:pnl,profit_pct:pnl*4,open_timestamp:start+(j*3+1)*86400000,close_timestamp:start+(j*3+2)*86400000,open_date:new Date(start+(j*3+1)*86400000).toISOString(),close_date:new Date(start+(j*3+2)*86400000).toISOString(),exit_reason:pnl>0?'roi':'stop_loss'}));
  const wins=recent.filter(t=>t.profit_abs>0);const losses=recent.filter(t=>t.profit_abs<0);
  bots[key]={key,label:i===2?'killers-scalp':key,name:key,reachable:true,dry_run:false,observed_at:now/1000,venue:i===2?'hyperliquid':'binance',account_group:i===2?'hl':'binance-spot',wallet:{bot_owned:100,starting_capital:100},pnl:{closed:i-1,unrealized:2,all_coin:i+1,all_pct:i+1},stats:{closed_trade_count:2,winning_trades:wins.length,losing_trades:losses.length,winrate:wins.length/2,max_drawdown:.016,gross_profit:wins.reduce((s,t)=>s+t.profit_abs,0),gross_loss:Math.abs(losses.reduce((s,t)=>s+t.profit_abs,0)),profit_factor:losses.length?wins.reduce((s,t)=>s+t.profit_abs,0)/Math.abs(losses.reduce((s,t)=>s+t.profit_abs,0)):null},capital_at_risk:{abs_loss:7.5},readiness:{label:'Waiting for entry conditions'},epoch:{version:'Current live epoch',start_ts_ms:start},open_trades:[{trade_id:i+1,pair,open_rate:100,current_rate:108,open_timestamp:start+6*86400000,profit_abs:2,profit_pct:8,stop_loss_abs:70,amount:.25,stake_amount:25,is_short:false,tps_total:2,tps_hit:0,next_tp:140,exit_levels:[{price:140,state:'active',label:'TP 1'},{price:160,state:'pending',label:'TP 2'}]}],recent_trades:recent,per_pair:[{pair,pnl:i-1,count:2}],drawdown_curve:[],baseline:{},history:{complete:true,count:2}};
  trades.push(...recent.map(t=>({...t,bot_key:key,open_ts:t.open_timestamp,close_ts:t.close_timestamp,bot:key,bot_label:bots[key].label,_bot:key,_botLabel:bots[key].label})));
  const realized=[[start,100],...recent.map((t,j)=>[t.close_timestamp,100+recent.slice(0,j+1).reduce((s,t)=>s+t.profit_abs,0)])];
  equities[key]={realized,live:[...realized,[now,101+i]],drawdown:[[start,0],[start+5*86400000,Math.min(0,i-1.6)],[now,0]],starting_capital:100,bot_start_ts_ms:start};
 });
 const state={bots,errors:{},last_poll:now/1000,status:{stale_bots:[]},account_health:{complete:true,equity:206,warnings:[],accounts:{'binance-spot':{equity:103,free:53,margin:0},hl:{equity:103,free:78,margin:25}}}};
 return {state,trades,response(path){if(path==='/api/state')return state;if(path==='/api/closed_trades')return {trades};if(path==='/api/killers/state')return {};if(path.includes('trade_candles'))return {candles:Array.from({length:150},(_,i)=>{const p=100+Math.sin(i/9)*3+i*.05;return [Math.floor((now-(150-i)*3600000)/3600000)*3600000,p,p+.3,p-1,p+1]})};if(path.startsWith('/api/equity/'))return equities[path.split('/').pop()]||{};return {};}};
};
