// Consistent, entirely synthetic data shared by the visual preview and browser tests.
module.exports = function fixture(now=Date.now()) {
 const start=now-12*86400000;const bots={};const equities={};const trades=[];
 // Exit policies mirror the shape of /api/state exit_policy; values are synthetic.
 const policies=[
  {roi:[[0,.08],[360,.05],[720,.03],[1440,.02]],stoploss:-.045,trailing:{enabled:false},rules:[{kind:'time',after_hours:96,profit_below:0,reason:'v2_failed_reversion'},{kind:'time',after_hours:168,profit_below:.01,reason:'v2_expired_episode'}],receiver_driven:false},
  {roi:[[0,.1],[360,.07],[720,.04],[1440,.02]],stoploss:-.06,trailing:{enabled:true,positive:.03,offset:.05,only_offset_reached:true},rules:[{kind:'time',after_hours:120,profit_below:0,reason:'v2_stale_bounce'}],receiver_driven:false},
  {roi:[[0,100]],stoploss:-.07,trailing:{enabled:false},rules:[],receiver_driven:true}];
 // An unfilled limit entry as /api/state reports it (#159): amount 0 and a resting buy order.
 const pendingEntry={trade_id:15,pair:'ENA/USDC:USDC',open_rate:.225,current_rate:.231,open_timestamp:now-3*3600000,profit_abs:0,profit_pct:0,stop_loss_abs:.21975,amount:0,amount_requested:413,stake_amount:30.98,is_short:false,leverage:3,posted_stop:.2,entry:{state:'pending',side:'buy',order_id:'synthetic-entry-15',order_type:'limit',price:.225,requested:413,filled:0,placed_ts:now-3*3600000,expires_ts:now+21*3600000,cancellable:true}};
 // A partially filled entry: a position exists, so it is not pending and not cancellable from the dashboard.
 const partialEntry={trade_id:21,pair:'OP/USDT',open_rate:2,current_rate:2.04,open_timestamp:now-6.5*86400000,profit_abs:.24,profit_pct:2,stop_loss_abs:1.88,amount:6,amount_requested:12.5,stake_amount:12,is_short:false,leverage:1,posted_stop:null,entry:{state:'partial',side:'buy',order_id:'synthetic-entry-21',order_type:'limit',price:2,requested:12.5,filled:6,placed_ts:now-6.5*86400000,expires_ts:now-6.5*86400000+600000,cancellable:false}};
 ['funding-fade','keltner-bounce','killers-ft'].forEach((key,i)=>{
  const pair=['TRX/USDT','FIL/USDT','LINK/USDC:USDC'][i];
  const recent=[.6,i-1.6].map((pnl,j)=>({trade_id:10+i*2+j,pair,is_open:false,open_rate:100,close_rate:100+pnl*4,amount:.25,stake_amount:25,profit_abs:pnl,profit_pct:pnl*4,open_timestamp:start+(j*3+1)*86400000,close_timestamp:start+(j*3+2)*86400000,open_date:new Date(start+(j*3+1)*86400000).toISOString(),close_date:new Date(start+(j*3+2)*86400000).toISOString(),exit_reason:pnl>0?'roi':'stop_loss'}));
  const wins=recent.filter(t=>t.profit_abs>0);const losses=recent.filter(t=>t.profit_abs<0);
  bots[key]={key,label:i===2?'killers-scalp':key,name:key,reachable:true,dry_run:false,observed_at:now/1000,venue:i===2?'hyperliquid':'binance',account_group:i===2?'hl':'binance-spot',wallet:{bot_owned:100,starting_capital:100},pnl:{closed:i-1,unrealized:2,all_coin:i+1,all_pct:i+1},stats:{closed_trade_count:2,winning_trades:wins.length,losing_trades:losses.length,winrate:wins.length/2,max_drawdown:.016,gross_profit:wins.reduce((s,t)=>s+t.profit_abs,0),gross_loss:Math.abs(losses.reduce((s,t)=>s+t.profit_abs,0)),profit_factor:losses.length?wins.reduce((s,t)=>s+t.profit_abs,0)/Math.abs(losses.reduce((s,t)=>s+t.profit_abs,0)):null},capital_at_risk:{abs_loss:7.5},readiness:{label:'Waiting for entry conditions'},epoch:{version:'Current live epoch',start_ts_ms:start},open_trades:[{trade_id:i+1,pair,open_rate:100,current_rate:108,open_timestamp:start+6*86400000,profit_abs:2,profit_pct:i===2?24:8,stop_loss_abs:70,amount:.25,stake_amount:25,is_short:false,leverage:i===2?3:1,tps_total:2,tps_hit:0,next_tp:140,exit_levels:[{price:140,state:'active',label:'TP 1'},{price:160,state:'pending',label:'TP 2'}]}].concat(i===2?[pendingEntry]:i===1?[partialEntry]:[]),exit_policy:policies[i],recent_trades:recent,realized_events:recent.map(t=>[t.close_timestamp,t.profit_abs]),per_pair:[{pair,pnl:i-1,count:2}],drawdown_curve:[],baseline:{},history:{complete:true,count:2}};
  trades.push(...recent.map(t=>({...t,bot_key:key,open_ts:t.open_timestamp,close_ts:t.close_timestamp,bot:key,bot_label:bots[key].label,_bot:key,_botLabel:bots[key].label})));
  const realized=[[start,100],...recent.map((t,j)=>[t.close_timestamp,100+recent.slice(0,j+1).reduce((s,t)=>s+t.profit_abs,0)])];
  equities[key]={realized,live:[...realized,[now,101+i]],drawdown:[[start,0],[start+5*86400000,Math.min(0,i-1.6)],[now,0]],starting_capital:100,bot_start_ts_ms:start};
 });
 const state={bots,errors:{},last_poll:now/1000,status:{stale_bots:[]},account_health:{complete:true,equity:206,warnings:[],accounts:{'binance-spot':{equity:103,free:53,margin:0},hl:{equity:103,free:78,margin:25}}}};
 return {state,trades,response(path){if(path==='/api/state')return state;if(path==='/api/closed_trades')return {trades};if(path==='/api/killers/state')return {};if(path.includes('trade_candles'))return {candles:Array.from({length:150},(_,i)=>{const p=100+Math.sin(i/9)*3+i*.05;return [Math.floor((now-(150-i)*3600000)/3600000)*3600000,p,p+.3,p-1,p+1]})};if(path.startsWith('/api/equity/'))return equities[path.split('/').pop()]||{};return {};}};
};
