const {chromium}=require('playwright');
const fs=require('fs');const root=require('path').join(__dirname,'../../');const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch(process.env.CHROME_CHANNEL?{channel:process.env.CHROME_CHANNEL}:{});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const now=Date.now();const start=now-6*86400000;const ts=now/1000;
 const bots={};for(const [i,key] of ['funding-fade','keltner-bounce','killers-ft'].entries()){bots[key]={key,label:key,name:key,reachable:true,dry_run:false,observed_at:ts,venue:i===2?'hyperliquid':'binance',account_group:i===2?'hl':'binance-spot',wallet:{bot_owned:100,starting_capital:100},pnl:{closed:i-1,unrealized:i+2,all_coin:2*i+1,all_pct:2*i+1},stats:{closed_trade_count:4,winning_trades:2,losing_trades:2,winrate:.5,max_drawdown:.02,profit_factor:.9},capital_at_risk:{abs_loss:2},readiness:{label:'Waiting for entry conditions'},epoch:{version:'Current live epoch'},open_trades:[{trade_id:i+1,pair:['TRX/USDT','FIL/USDT','LINK/USDC:USDC'][i],open_rate:100,current_rate:108,open_timestamp:start,profit_abs:2,profit_pct:8,stop_loss_abs:70,amount:1,stake_amount:100,is_short:false,tps_total:2,tps_hit:0,next_tp:140,exit_levels:[{price:140,state:'active',label:'TP 1'},{price:160,state:'pending',label:'TP 2'}]}],recent_trades:[],per_pair:[],drawdown_curve:[],baseline:{},history:{complete:true,count:4}};}
 const state={bots,errors:{},last_poll:ts,status:{stale_bots:[]},account_health:{complete:true,equity:209,warnings:[]}};
 await page.route('**/*',async route=>{const url=new URL(route.request().url());if(url.pathname.includes('alpine'))return route.fulfill({path:require.resolve('alpinejs/dist/cdn.min.js'),contentType:'text/javascript'});if(url.pathname.includes('echarts'))return route.fulfill({path:require.resolve('echarts/dist/echarts.min.js'),contentType:'text/javascript'});if(url.pathname==='/api/state')return route.fulfill({json:state});if(url.pathname==='/api/closed_trades')return route.fulfill({json:{trades:[]}});if(url.pathname==='/api/killers/state')return route.fulfill({json:{}});if(url.pathname.includes('trade_candles')){const candles=Array.from({length:150},(_,i)=>{let p=100+Math.sin(i/9)*3+i*.05;return [Math.floor((now-(150-i)*3600000)/3600000)*3600000,p,p+.3,p-1,p+1]});return route.fulfill({json:{candles}});}if(url.pathname.includes('/api/'))return route.fulfill({json:{realized:[[start,100],[now,101]],live:[[start,100],[now,103]],drawdown:[[start,0],[now,-1]],starting_capital:100,bot_start_ts_ms:start}});if(url.pathname.startsWith('/static/'))return route.fulfill({path:root+url.pathname.slice(1)});if(url.hostname==='dashboard.test')return route.fulfill({body:fs.readFileSync(root+'templates/index.html','utf8').replace('master-trader<span>','master-trader · Preview<span>'),contentType:'text/html'});return route.abort();});
 await page.goto('http://dashboard.test/');await page.waitForTimeout(1800);
 await page.getByRole('button',{name:/^positions/}).first().click();await page.waitForTimeout(1000);
 await page.getByRole('button',{name:'All exits',exact:true}).first().click();await page.getByRole('button',{name:'Expand chart',exact:true}).first().click();await page.waitForTimeout(400); assert.equal(await page.locator('.trade-card.expanded').count(),1);const expanded=await page.locator('.trade-card.expanded .trade-chart').boundingBox();assert(expanded.width>1200&&expanded.height>=600);
 await page.keyboard.press('Escape');assert.equal(await page.locator('.trade-card.expanded').count(),0);await page.setViewportSize({width:390,height:844});await page.waitForTimeout(400);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.setViewportSize({width:1440,height:1000}); await page.evaluate(()=>Alpine.$data(document.body).setTab('bot:killers-ft'));await page.waitForTimeout(500);
 assert.deepEqual(errors,[]);console.log('Workspace overview, positions, expansion, Escape, mobile and bot detail passed');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
