"""Re-simulate the Insiders Scalp 83-day replay using WEEX historical prices.

Reads `docs/insiders-signals/replay/trades_llm_2026-05-26.json` (Dennis's
147 sized trades over 83 days, +$763.96 / +76.4% baseline on Binance) and
walks each trade's WEEX 1m candles to compute what would have actually
happened on Dennis's venue.

Important methodology note (apples-to-apples):
  The trade JSON's `scaled_pnl` values were generated by an earlier version
  of `resolve_exits` whose behavior we cannot fully reproduce. Comparing our
  WEEX walk to those numbers conflates two effects: (1) the venue-price
  difference and (2) the resolve_exits methodology drift.

  To isolate effect (1), we ALSO recompute the Binance baseline with the
  same walker we use on WEEX. That gives a clean delta:
    apples_binance_total  ←  same walker, Binance prices
    apples_weex_total     ←  same walker, WEEX prices
  Both are reported alongside the JSON's `binance_baseline_pnl`.

Walker semantics (mirrors `ft_userdata/insiders_bridge/_local/weex.py`):
  - Uses ONLY the original SL/TP from the trade payload (no move_sl /
    close_partial / increase events apply, consistent with the Binance sim).
  - If a close_full event exists, the walk window ends at that event's minute.
  - If neither SL nor TP fires in the walk, exits at last candle close
    (reason='manual' if there was a close_full, else 'open').
  - Walk capped at BINANCE_KLINE_LIMIT minutes past entry (replicates the
    original sim's get_klines limit=1000 behavior).
  - Market entry: next-minute open after signal timestamp.
  - Limit entry: first minute whose low<=entry (long) or high>=entry (short).
  - Conservative TP/SL ordering: TP checked first within candle (matches sim).

WEEX symbol mapping (probed against api-contract.weex.com):
  - Most coins:   cmt_{lower}usdt           e.g. cmt_btcusdt
  - PEPE / 1000PEPE: cmt_1000pepeusdt        same scale as `1000PEPE` in trades
  - XTIU: NOT LISTED — trades marked weex_unavailable

Output:
  weex_probe/replay_on_weex_output.json — per-trade + summary

Read-only on docs/insiders-signals/replay/trades_llm_2026-05-26.json.
"""
from __future__ import annotations

import json
import os
import sys
import time
from collections import defaultdict
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Optional

import requests

HERE = Path(__file__).parent
ROOT = HERE.parent
TRADES_PATH = ROOT / "docs/insiders-signals/replay/trades_llm_2026-05-26.json"
CACHE_DIR = HERE / "historical_klines"
OUTPUT_PATH = HERE / "replay_on_weex_output.json"

WEEX_HISTORY_URL = "https://api-contract.weex.com/capi/v2/market/historyCandles"
WEEX_KLINES_MAX = 100         # endpoint cap
BINANCE_FAPI_URL = "https://fapi.binance.com/fapi/v1/klines"
BINANCE_KLINES_MAX = 1500     # endpoint cap (we use 1000 for sim parity)
RATE_LIMIT_HZ = 12            # stay under WEEX 20 req/s ceiling

ACCOUNT_USD = 1000.0          # baseline notional
RISK_PER_TRADE_USD = 10.0     # per the original sim
MARGIN_PER_TRADE_USD = 50.0   # per the original sim
HARD_TIMEOUT_DAYS = 14        # cap how long we'll walk an unclosed trade
NEXT_MINUTE_BUFFER_MS = 60_000

# The original Binance simulator (ft_userdata/insiders_bridge/_local/weex.py)
# calls `get_klines(..., limit=1000)`, capping each trade's candle walk at the
# first 1000 minutes (~16.6h) after the entry signal. We replicate that cap so
# the comparison isolates the venue-price effect, not the simulator's bug.
# Set to None to walk the full window (apples-to-oranges to original +$763.96).
BINANCE_KLINE_LIMIT = 1000


# Symbols Dennis trades that are NOT on WEEX (confirmed via probe)
WEEX_UNAVAILABLE = {"XTIU"}

# Symbols that need a 1000-prefix on WEEX (price × 0.001 to match Binance scale)
WEEX_1000_PREFIX = {"PEPE"}


# ── Cache + fetch ───────────────────────────────────────────────────────────

def weex_symbol(symbol: str) -> Optional[str]:
    """Map a trade symbol (e.g. 'BTC', '1000PEPE') to WEEX historyCandles."""
    s = symbol.upper()
    if s in WEEX_UNAVAILABLE:
        return None
    if s == "1000PEPE":
        return "cmt_1000pepeusdt"
    if s == "PEPE":  # shouldn't occur but defensive
        return "cmt_1000pepeusdt"
    return f"cmt_{s.lower()}usdt"


def price_scale(symbol: str) -> float:
    """Multiplier to convert WEEX-quoted price into trade-quoted price.

    For 1000PEPE: WEEX shows price for 1000 tokens; trade is denominated in
    1000-token units (same!) so scale = 1.0. The trade JSON has symbol
    `1000PEPE` and prices already in the 1000-token quote, so no rescale.
    """
    return 1.0


_last_request_ts = [0.0]


def _rate_limit():
    min_gap = 1.0 / RATE_LIMIT_HZ
    elapsed = time.monotonic() - _last_request_ts[0]
    if elapsed < min_gap:
        time.sleep(min_gap - elapsed)
    _last_request_ts[0] = time.monotonic()


def fetch_weex_candles(symbol: str, start_ms: int, end_ms: int) -> list[dict]:
    """Fetch 1m WEEX candles in [start_ms, end_ms]. Returns oldest-first.

    Paginates 100-at-a-time. Returns [] on error (logged to stderr).
    """
    wex = weex_symbol(symbol)
    if wex is None:
        return []
    out = []
    cursor_end = end_ms
    seen_times = set()
    while cursor_end > start_ms:
        _rate_limit()
        try:
            r = requests.get(
                WEEX_HISTORY_URL,
                params={
                    "symbol": wex,
                    "granularity": "1m",
                    "startTime": start_ms,
                    "endTime": cursor_end,
                    "limit": WEEX_KLINES_MAX,
                    "priceType": "LAST",
                },
                timeout=15,
            )
            data = r.json()
        except Exception as e:
            print(f"  [WARN] fetch {wex} err: {e}", file=sys.stderr)
            break
        if not isinstance(data, list):
            print(f"  [WARN] fetch {wex} non-list: {data}", file=sys.stderr)
            break
        if not data:
            break
        # WEEX returns newest-first; iterate oldest to newest for cursor
        rows_sorted = sorted(data, key=lambda r: int(r[0]))
        new_rows = 0
        for row in rows_sorted:
            t = int(row[0])
            if t in seen_times:
                continue
            seen_times.add(t)
            out.append({
                "t": t,
                "o": float(row[1]),
                "h": float(row[2]),
                "l": float(row[3]),
                "c": float(row[4]),
                "v": float(row[5]),
            })
            new_rows += 1
        if new_rows == 0:
            break
        # Move cursor backward: next request ends just before the oldest we have
        oldest_t = min(int(r[0]) for r in rows_sorted)
        if oldest_t <= start_ms:
            break
        cursor_end = oldest_t - 1
    out.sort(key=lambda c: c["t"])
    return out


def cache_path(symbol: str, venue: str = "weex") -> Path:
    suffix = "" if venue == "weex" else f".{venue}"
    return CACHE_DIR / f"{symbol.upper()}{suffix}.jsonl"


def load_cache(symbol: str, venue: str = "weex") -> dict[int, dict]:
    p = cache_path(symbol, venue)
    if not p.exists():
        return {}
    out = {}
    for line in p.read_text().splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            c = json.loads(line)
            out[int(c["t"])] = c
        except Exception:
            pass
    return out


def append_cache(symbol: str, candles: list[dict], venue: str = "weex") -> None:
    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    p = cache_path(symbol, venue)
    with p.open("a") as f:
        for c in candles:
            f.write(json.dumps(c) + "\n")


def fetch_binance_candles(symbol: str, start_ms: int, end_ms: int) -> list[dict]:
    """Fetch 1m Binance fapi candles in [start_ms, end_ms], oldest-first.

    Paginates 1500-at-a-time. Returns [] if symbol not listed or error.
    """
    pair = symbol.upper()
    if pair == "1000PEPE":
        pair = "1000PEPEUSDT"
    elif not pair.endswith("USDT"):
        pair = f"{pair}USDT"
    out = []
    cursor = start_ms
    seen = set()
    while cursor < end_ms:
        _rate_limit()
        try:
            r = requests.get(BINANCE_FAPI_URL, params={
                "symbol": pair, "interval": "1m",
                "startTime": cursor, "endTime": end_ms,
                "limit": BINANCE_KLINES_MAX,
            }, timeout=15)
            data = r.json()
        except Exception as e:
            print(f"  [WARN] binance fetch {pair} err: {e}", file=sys.stderr)
            break
        if not isinstance(data, list) or not data:
            break
        new_rows = 0
        for row in data:
            t = int(row[0])
            if t in seen:
                continue
            seen.add(t)
            out.append({
                "t": t, "o": float(row[1]), "h": float(row[2]),
                "l": float(row[3]), "c": float(row[4]), "v": float(row[5]),
            })
            new_rows += 1
        if new_rows == 0:
            break
        cursor = int(data[-1][0]) + 60_000
    out.sort(key=lambda c: c["t"])
    return out


def get_candles(symbol: str, start_ms: int, end_ms: int, venue: str = "weex") -> list[dict]:
    """Return all 1m candles in [start_ms, end_ms] for `venue`. Caches per-symbol.

    venue: 'weex' (uses WEEX historyCandles, paginated 100/req)
           'binance' (uses Binance fapi, paginated 1500/req)
    """
    cache = load_cache(symbol, venue)
    # Identify gaps. Simple approach: if our cache covers anything in range, check
    # coverage; otherwise fetch the whole range.
    # Round to minute boundaries
    start_minute = start_ms - (start_ms % 60_000)
    end_minute = end_ms - (end_ms % 60_000)
    if end_minute < start_minute:
        return []

    expected_count = (end_minute - start_minute) // 60_000 + 1
    have = sum(1 for t in cache if start_minute <= t <= end_minute)

    # We allow up to 5% missing minutes — WEEX sometimes has no-trade gaps for
    # illiquid alt pairs. If coverage is below that, refetch the range.
    if have < expected_count * 0.95:
        if venue == "binance":
            new_candles = fetch_binance_candles(symbol, start_minute, end_minute)
        else:
            new_candles = fetch_weex_candles(symbol, start_minute, end_minute)
        if new_candles:
            fresh = [c for c in new_candles if c["t"] not in cache]
            if fresh:
                append_cache(symbol, fresh, venue)
                for c in fresh:
                    cache[c["t"]] = c
    out = [c for t, c in cache.items() if start_minute <= t <= end_minute]
    out.sort(key=lambda c: c["t"])
    return out


# ── Replay logic ────────────────────────────────────────────────────────────

def parse_dt(s: str) -> datetime:
    return datetime.fromisoformat(s.replace("Z", "+00:00"))


def ms(s: str) -> int:
    return int(parse_dt(s).timestamp() * 1000)


def compute_trade_window(trade: dict) -> tuple[int, int]:
    """Return (start_ms, end_ms) for kline fetch.

    To mirror the Binance sim, we cap the fetch window at:
      max(close_full_ts, +1000 minutes from entry, +HARD_TIMEOUT_DAYS)
    The actual walk is further capped at the BINANCE_KLINE_LIMIT in simulate_trade.
    """
    start_ms = ms(trade["date"])
    # End at first close_full event if present, else hard timeout
    close_full_ms = None
    for e in trade.get("events") or []:
        if e.get("kind") == "close_full":
            close_full_ms = ms(e["date"])
            break
    if close_full_ms is not None:
        end_ms = close_full_ms + 60_000  # +1m buffer
    else:
        end_ms = start_ms + HARD_TIMEOUT_DAYS * 24 * 3600 * 1000
    # Apply Binance kline limit cap to keep fetches small
    if BINANCE_KLINE_LIMIT is not None:
        end_ms = min(end_ms, start_ms + (BINANCE_KLINE_LIMIT + 60) * 60_000)
    return start_ms, end_ms


def find_candle(candles: list[dict], minute_ms: int) -> Optional[dict]:
    """Linear scan — fine for ≤ ~20k candles per trade window."""
    for c in candles:
        if c["t"] == minute_ms:
            return c
    return None


def find_index(candles: list[dict], minute_ms: int) -> int:
    """Binary search; returns index of first candle with t >= minute_ms."""
    lo, hi = 0, len(candles)
    while lo < hi:
        mid = (lo + hi) // 2
        if candles[mid]["t"] < minute_ms:
            lo = mid + 1
        else:
            hi = mid
    return lo


def simulate_trade(trade: dict, candles: list[dict]) -> dict:
    """Re-simulate one trade on WEEX candles.

    Mirrors the Binance sim's `resolve_exits` semantics exactly (so the
    comparison isolates the venue-price effect, not the simulator semantics):
      - Uses ONLY the original SL/TP from the trade payload.
      - Does NOT apply move_sl / close_partial / increase events (consistent
        with the Binance sim, which ignores them when walking candles).
      - The close_full event timestamp bounds the walk window — if neither SL
        nor TP fires before that timestamp, the trade exits at the last
        available candle close as "manual".
      - Otherwise walks to the end of available candles ("open").

    Entry semantics:
      - Market entry: next-minute open after signal timestamp.
      - Limit entry (long): first minute whose low <= entry price.
      - Limit entry (short): first minute whose high >= entry price.

    Returns a result dict with weex_entry_price, weex_exit_price,
    weex_exit_reason, weex_pnl_pct, weex_scaled_pnl, notes.
    """
    notes = []
    if not candles:
        return {
            "weex_entry_price": None,
            "weex_exit_price": None,
            "weex_exit_reason": "no_data",
            "weex_pnl_pct": None,
            "weex_scaled_pnl": None,
            "notes": ["no_weex_candles"],
        }

    direction = trade["direction"].upper()
    entry_price = trade.get("entry")
    if entry_price is None:
        return {
            "weex_entry_price": None,
            "weex_exit_price": None,
            "weex_exit_reason": "no_data",
            "weex_pnl_pct": None,
            "weex_scaled_pnl": None,
            "notes": ["trade_has_no_entry"],
        }
    entry_price = float(entry_price)

    entry_minute = ms(trade["date"]) - (ms(trade["date"]) % 60_000)
    start_idx = find_index(candles, entry_minute)
    if start_idx >= len(candles):
        return {
            "weex_entry_price": None,
            "weex_exit_price": None,
            "weex_exit_reason": "no_data",
            "weex_pnl_pct": None,
            "weex_scaled_pnl": None,
            "notes": ["no_candle_at_entry"],
        }

    # ── Entry fill ──────────────────────────────────────────────────────────
    # Match the Binance sim's assumption: the trade IS opened at `trade.entry`
    # regardless of whether the venue's price crossed it. The Binance sim does
    # not check entry-fill — it walks candles from signal time forward, treating
    # trade.entry as the cost basis. We mirror that for apples-to-apples.
    # We DO still mark trades whose entry is far from the venue's price as
    # likely-missed for diagnostic purposes (note added; PnL still computed).
    entry_candle = candles[start_idx]
    weex_entry_idx = start_idx

    if trade.get("market_entry"):
        # Market: next-minute open after signal
        if start_idx + 1 < len(candles):
            weex_entry = candles[start_idx + 1]["o"]
            weex_entry_idx = start_idx + 1
        else:
            weex_entry = entry_candle["c"]
            notes.append("market_entry_last_candle_close")
    else:
        # Limit: use the trade's specified entry price as cost basis.
        weex_entry = entry_price
        # Diagnostic: would this entry actually have filled in the venue's price
        # action? (Long: low<=entry within walk window; Short: high>=entry)
        would_fill = False
        for i in range(start_idx, min(start_idx + 100, len(candles))):  # 100min look-ahead
            c = candles[i]
            if direction == "LONG" and c["l"] <= entry_price:
                would_fill = True
                weex_entry_idx = i
                break
            if direction == "SHORT" and c["h"] >= entry_price:
                would_fill = True
                weex_entry_idx = i
                break
        if not would_fill:
            notes.append("likely_unfilled_in_100min_window")

    # ── Determine walk-end (matches Binance sim) ────────────────────────────
    # If channel posted a close_full, walk stops at that event's minute.
    close_full_ms = None
    for e in trade.get("events") or []:
        if e.get("kind") == "close_full":
            close_full_ms = ms(e["date"])
            break  # use the first close_full only

    end_idx = len(candles)
    if close_full_ms is not None:
        end_minute = close_full_ms - (close_full_ms % 60_000)
        ei = find_index(candles, end_minute)
        end_idx = min(ei + 1, len(candles))  # inclusive of close_full minute

    # Replicate the Binance sim's limit=1000 cap (1000 candles past entry).
    if BINANCE_KLINE_LIMIT is not None:
        end_idx = min(end_idx, weex_entry_idx + BINANCE_KLINE_LIMIT)

    # ── Walk for SL/TP ──────────────────────────────────────────────────────
    sl = trade.get("sl")
    if isinstance(sl, str):
        sl = None
    tp = trade.get("tp")
    if isinstance(tp, str):
        tp = None

    exit_price = None
    exit_reason = None

    for i in range(weex_entry_idx, end_idx):
        c = candles[i]
        high, low = c["h"], c["l"]
        if direction == "LONG":
            # Binance sim checks TP first inside its loop, then SL. Mirror.
            if tp and high >= tp:
                exit_price = tp
                exit_reason = "tp"
                break
            if sl and low <= sl:
                exit_price = sl
                exit_reason = "sl"
                break
        else:  # SHORT
            if tp and low <= tp:
                exit_price = tp
                exit_reason = "tp"
                break
            if sl and high >= sl:
                exit_price = sl
                exit_reason = "sl"
                break

    if exit_price is None:
        # Fallback exit: last candle close in walk window
        last_c = candles[end_idx - 1] if end_idx > 0 else candles[-1]
        exit_price = last_c["c"]
        if close_full_ms is not None:
            exit_reason = "manual"
        else:
            exit_reason = "open"

    # Compute PnL
    if direction == "LONG":
        pnl_pct = (exit_price - weex_entry) / weex_entry
    else:
        pnl_pct = (weex_entry - exit_price) / weex_entry

    notional = trade.get("position_notional") or 0.0
    weex_scaled_pnl = round(notional * pnl_pct, 2)

    return {
        "weex_entry_price": weex_entry,
        "weex_exit_price": exit_price,
        "weex_exit_reason": exit_reason,
        "weex_pnl_pct": pnl_pct,
        "weex_scaled_pnl": weex_scaled_pnl,
        "notes": notes,
    }


# ── Main ────────────────────────────────────────────────────────────────────


def aggregate(results: list, key_prefix: str) -> dict:
    """Compute summary stats for either 'weex_' or 'apples_binance_' results."""
    pnl_key = f"{key_prefix}scaled_pnl"
    reason_key = f"{key_prefix}exit_reason"
    pnl_total = sum(r[pnl_key] or 0 for r in results)
    n_missed = sum(1 for r in results if r[reason_key] == "missed_entry")
    n_unavail = sum(1 for r in results if r[reason_key] == "weex_unavailable")
    n_no_data = sum(1 for r in results if r[reason_key] == "no_data")
    n_executed = sum(1 for r in results if r[pnl_key] is not None
                     and r[reason_key] not in ("missed_entry", "weex_unavailable", "no_data"))
    wins = [r for r in results if (r[pnl_key] or 0) > 0]
    losses = [r for r in results if (r[pnl_key] or 0) < 0]
    win_rate = len(wins) / max(1, n_executed)
    gross_win = sum(r[pnl_key] for r in wins)
    gross_loss = -sum(r[pnl_key] for r in losses)
    pf = (gross_win / gross_loss) if gross_loss > 0 else None

    # Max drawdown on chronological equity curve
    sorted_r = sorted(results, key=lambda r: r["date"])
    equity = ACCOUNT_USD
    peak = ACCOUNT_USD
    max_dd_pct = 0.0
    for r in sorted_r:
        equity += r[pnl_key] or 0
        peak = max(peak, equity)
        dd = (peak - equity) / peak if peak > 0 else 0
        max_dd_pct = max(max_dd_pct, dd)

    return {
        "total_pnl": round(pnl_total, 2),
        "return_pct": round(pnl_total / ACCOUNT_USD * 100, 2),
        "n_executed": n_executed,
        "n_missed_entries": n_missed,
        "n_unavailable": n_unavail,
        "n_no_data": n_no_data,
        "win_rate": round(win_rate, 4),
        "profit_factor": round(pf, 3) if pf is not None else None,
        "max_drawdown_pct": round(max_dd_pct * 100, 2),
    }


def main():
    if not TRADES_PATH.exists():
        print(f"ERROR: {TRADES_PATH} not found", file=sys.stderr)
        sys.exit(1)
    data = json.loads(TRADES_PATH.read_text())
    all_trades = data["trades"]
    trades = [t for t in all_trades if t.get("scaled_pnl") is not None]
    print(f"Loaded {len(all_trades)} trades, {len(trades)} sized")

    by_symbol = defaultdict(list)
    for t in trades:
        by_symbol[t["symbol"]].append(t)
    print(f"Symbols: {len(by_symbol)}")

    results = []
    for sym in sorted(by_symbol.keys()):
        sym_trades = by_symbol[sym]
        print(f"  {sym}: {len(sym_trades)} trades")

        for t in sym_trades:
            start_ms, end_ms = compute_trade_window(t)

            # ── WEEX walk ───────────────────────────────────────────────────
            if sym in WEEX_UNAVAILABLE:
                wr = {
                    "weex_entry_price": None,
                    "weex_exit_price": None,
                    "weex_exit_reason": "weex_unavailable",
                    "weex_pnl_pct": None,
                    "weex_scaled_pnl": None,
                    "notes": ["symbol_not_on_weex"],
                }
            else:
                try:
                    candles_w = get_candles(sym, start_ms, end_ms, venue="weex")
                except Exception as e:
                    print(f"    trade {t['msg_id']} WEEX fetch err: {e}", file=sys.stderr)
                    candles_w = []
                wr_raw = simulate_trade(t, candles_w)
                wr = {f"weex_{k.replace('weex_', '')}" if k.startswith("weex_") else f"weex_{k}": v
                      for k, v in wr_raw.items()}
                # The simulate_trade already returns weex_* keys
                wr = {k: wr_raw[k] for k in (
                    "weex_entry_price", "weex_exit_price", "weex_exit_reason",
                    "weex_pnl_pct", "weex_scaled_pnl", "notes",
                )}

            # ── Apples-to-apples Binance walk ────────────────────────────────
            # Mirrors the original sim's `get_klines`: try Binance fapi first,
            # fall back to WEEX historyCandles for symbols not (yet) on Binance.
            try:
                candles_b = get_candles(sym, start_ms, end_ms, venue="binance")
            except Exception as e:
                print(f"    trade {t['msg_id']} Binance fetch err: {e}", file=sys.stderr)
                candles_b = []
            # Cover gap: if Binance returned less than half the expected minutes,
            # the symbol likely wasn't listed yet — fall back to WEEX prices.
            expected = max(1, (end_ms - start_ms) // 60_000)
            if len(candles_b) < expected * 0.5 and sym not in WEEX_UNAVAILABLE:
                try:
                    candles_b = get_candles(sym, start_ms, end_ms, venue="weex")
                except Exception:
                    pass
            br_raw = simulate_trade(t, candles_b)
            br = {
                "apples_binance_entry_price": br_raw["weex_entry_price"],
                "apples_binance_exit_price": br_raw["weex_exit_price"],
                "apples_binance_exit_reason": br_raw["weex_exit_reason"],
                "apples_binance_pnl_pct": br_raw["weex_pnl_pct"],
                "apples_binance_scaled_pnl": br_raw["weex_scaled_pnl"],
            }

            results.append({**t, **wr, **br})
        print(f"    done.")

    # ── Aggregate ──────────────────────────────────────────────────────────
    weex_stats = aggregate(results, "weex_")
    apples_stats = aggregate(results, "apples_binance_")

    pnl_json = sum(t["scaled_pnl"] for t in trades)

    # Per-symbol delta (apples-to-apples: same simulator both venues)
    sym_deltas = defaultdict(lambda: {"apples_binance": 0.0, "weex": 0.0, "n": 0,
                                       "json_binance": 0.0})
    for r in results:
        s = r["symbol"]
        sym_deltas[s]["apples_binance"] += r["apples_binance_scaled_pnl"] or 0
        sym_deltas[s]["weex"] += r["weex_scaled_pnl"] or 0
        sym_deltas[s]["json_binance"] += r["scaled_pnl"] or 0
        sym_deltas[s]["n"] += 1
    deltas = [(s, d["apples_binance"], d["weex"], d["weex"] - d["apples_binance"],
               d["json_binance"], d["n"])
              for s, d in sym_deltas.items()]
    deltas.sort(key=lambda x: abs(x[3]), reverse=True)

    # Missed-entry diagnostic: trades whose limit entry would not have filled
    # on WEEX within 100 minutes of signal (cost basis still used = trade.entry)
    likely_unfilled_weex = [
        r for r in results
        if r.get("notes") and "likely_unfilled_in_100min_window" in r["notes"]
    ]
    no_data_trades = [r for r in results if r["weex_exit_reason"] == "no_data"]

    summary = {
        "json_baseline": {
            "total_pnl": round(pnl_json, 2),
            "return_pct": round(pnl_json / ACCOUNT_USD * 100, 2),
            "note": "Original Binance replay output from trades_llm_2026-05-26.json. "
                    "Generated with an older resolve_exits; methodology drift vs current walker.",
        },
        "apples_binance": {
            **apples_stats,
            "note": "Recomputed Binance baseline with the SAME walker used on WEEX.",
        },
        "weex": {
            **weex_stats,
            "note": "Same walker applied to WEEX historyCandles prices.",
        },
        "venue_delta_apples": {
            "pnl_delta_usd": round(weex_stats["total_pnl"] - apples_stats["total_pnl"], 2),
            "return_delta_pct": round(weex_stats["return_pct"] - apples_stats["return_pct"], 2),
        },
        "likely_unfilled_on_weex": [
            {"msg_id": r["msg_id"], "symbol": r["symbol"], "date": r["date"],
             "entry": r["entry"], "direction": r["direction"]}
            for r in likely_unfilled_weex
        ],
        "no_data_trades": [
            {"msg_id": r["msg_id"], "symbol": r["symbol"], "date": r["date"]}
            for r in no_data_trades
        ],
        "top_symbol_deltas": [
            {"symbol": s, "apples_binance": round(b, 2), "weex": round(w, 2),
             "delta": round(d, 2), "json_binance": round(jb, 2), "n_trades": n}
            for s, b, w, d, jb, n in deltas[:10]
        ],
    }

    OUTPUT_PATH.write_text(json.dumps({
        "summary": summary,
        "trades": results,
    }, indent=2, default=str))

    # ── Print summary ──────────────────────────────────────────────────────
    print()
    print("=" * 70)
    print("WEEX REPLAY SUMMARY")
    print("=" * 70)
    print(f"{'JSON baseline (orig sim)':30s}  ${pnl_json:+8.2f}  ({pnl_json/ACCOUNT_USD*100:+6.2f}%)")
    print(f"{'Apples Binance (this walker)':30s}  ${apples_stats['total_pnl']:+8.2f}  "
          f"({apples_stats['return_pct']:+6.2f}%)")
    print(f"{'WEEX (this walker)':30s}  ${weex_stats['total_pnl']:+8.2f}  "
          f"({weex_stats['return_pct']:+6.2f}%)")
    print(f"{'Venue delta (WEEX-Binance)':30s}  ${weex_stats['total_pnl']-apples_stats['total_pnl']:+8.2f}  "
          f"({weex_stats['return_pct']-apples_stats['return_pct']:+6.2f}pp)")
    print()
    print(f"{'Metric':30s}  {'Apples-Binance':>15s}  {'WEEX':>15s}")
    print(f"{'-'*30}  {'-'*15}  {'-'*15}")
    print(f"{'Trades executed':30s}  {apples_stats['n_executed']:>15d}  {weex_stats['n_executed']:>15d}")
    print(f"{'Missed entries':30s}  {apples_stats['n_missed_entries']:>15d}  {weex_stats['n_missed_entries']:>15d}")
    print(f"{'Symbols not listed':30s}  {apples_stats['n_unavailable']:>15d}  {weex_stats['n_unavailable']:>15d}")
    print(f"{'Win rate':30s}  {apples_stats['win_rate']*100:>14.1f}%  {weex_stats['win_rate']*100:>14.1f}%")
    pf_a = f"{apples_stats['profit_factor']:.2f}" if apples_stats['profit_factor'] else "n/a"
    pf_w = f"{weex_stats['profit_factor']:.2f}" if weex_stats['profit_factor'] else "n/a"
    print(f"{'Profit factor':30s}  {pf_a:>15s}  {pf_w:>15s}")
    print(f"{'Max drawdown':30s}  {apples_stats['max_drawdown_pct']:>14.2f}%  {weex_stats['max_drawdown_pct']:>14.2f}%")
    print()
    print("Top 10 |WEEX - apples-Binance| symbol deltas:")
    print(f"  {'sym':10s}  {'apples-BN':>10s}  {'WEEX':>10s}  {'delta':>10s}  {'json-BN':>10s}  n")
    for s, b, w, d, jb, n in deltas[:10]:
        print(f"  {s:10s}  ${b:+9.2f}  ${w:+9.2f}  ${d:+9.2f}  ${jb:+9.2f}  {n}")
    print()
    print(f"Likely unfilled on WEEX (cost basis used anyway): {len(likely_unfilled_weex)} trades")
    print(f"No-data trades on WEEX:  {len(no_data_trades)} trades")
    print()
    print(f"Wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
